version: "3"
services:
  cronjob:
    build: .
    image: "ali00h/cronjob_without_volume"
    container_name: cronjob-without-volume
    restart: always
    environment:
      - TZ=Asia/Tehran
      - CRON_LIST=* * * * * echo "cron test for each minutes",* * * * * wget "https://alihashemi.ir/pp/counter.php?p=1"
    volumes:
      - /c/Ali/Temp/cronlog/:/var/log/cronlog/      