version: "3"
services:
  cronjob:
    build: .
    image: "ali00h/cronjob_without_volume"
    container_name: cronjob-without-volume
    restart: always
    ports:
      - "8099:80"
    environment:
      - TZ=Asia/Tehran
      - LOG_MAX_LINE_COUNT=1000
      - CRON_LIST=* * * * * echo "cron test for each minutes",* * * * * wget "https://alihashemi.ir/pp/counter.php?p=1"
      - LOGIN_USERNAME=admin
      - LOGIN_PASSWORD=admin
    volumes:
      - /c/Ali/Temp/cronlog/:/var/log/cronlog/
      - ./code/webui/app:/var/www/html/webui/app